#!/bin/bash



pandoc --toc  \
    -o granadaoff.doc granada.txt  text/prologue.md text/tips.md \
    text/earthquakes.md text/off-limits.md  text/water.md text/snow.md \
    text/roundabouts.md text/train-station.md  text/freemasonry.md\
    text/buskers.md text/whorehouses.md  text/eccentrics-and-oddballs.md \
    text/danger-castle.md text/haunted.md text/fast-food.md \
    text/university.md text/geekery.md\
    text/graffiti.md
    coda.txt



