#!/bin/bash



pandoc -S --toc --epub-metadata=metadata.xml --epub-stylesheet=granadaoff.css \
    -o granadaoff.epub granada.txt  text/prologue.md text/tips.md text/off-limits.md text/snow.md\
    text/whorehouses.md text/roundabouts.md text/train-station.md\
    text/haunted.md text/buskers.md\
    text/danger-castle.md text/fast-food.md text/water.md \
    text/eccentrics-and-oddbals.md  
   



