#!/bin/bash

# Cambia la plantilla de latex al directorio donde esté

files=`cat files`
file_argument=''
for file in $files; do
    file_argument="$file_argument text/$file"
done
pandoc --verbose --template="$PWD"/template.latex \
     -V language=english -V lang=english \
     -V author='JJ Merelo' -V title='Granada on'\
     -V documentclass=book\
     -S --latex-engine=xelatex  \
     -o granadaon.pdf $file_argument coda.txt --toc



