#!/bin/bash

# Cambia la plantilla de latex al directorio donde esté

pandoc --verbose --template=plantilla.latex \
    -V language=spanish -V lang=spanish \
    -V author='JJ Merelo' -V title='Granada on'\
    -V documentclass=book\
    -S --latex-engine=xelatex  \
    -o granadaon.pdf \
    text/prologue.md text/tips.md text/hopscotch.md\
    text/earthquakes.md text/off-limits.md text/water.md text/snow.md text/barranco-abogado.md\
    text/holy-not-a-week.md \
    text/roundabouts.md text/train-station.md text/suburban-malls.md\
    text/freemasonry.md text/kasbah-teashops.md \
    text/buskers.md text/whorehouses.md  text/eccentrics-and-oddballs.md \
    text/danger-castle.md text/haunted.md text/cemetery.md\
    text/fast-food.md \
    text/university.md text/geekery.md\
    text/graffiti.md \
    coda.txt --toc



